### ISSUE TITLE
article

### ISSUE THREAD

**Issue by xiaoyudanaa** [xjixzz/van_depth#1]
Very unexpected to see this code, your coding ability is really admirable. I would like to read the related articles on this code and look forward to your reply

**Comment by xiaoyudanaa** [comment]
In addition, I would like to ask, how is the performance of VAN-depth

**Comment by xjixzz** [comment]
Thanks for your attention to this project. This code is mainly based on [monodepth2](https://github.com/nianticlabs/monodepth2) and [VAN](https://github.com/Visual-Attention-Network/VAN-Classification) so you might be interested in the papers of monodepth2 and VAN.

The test results on the Eigen split of KITTI with the MS (Monocular+Stereo) mode are as follows:

-> Computing predictions with size 640x192
-> Evaluating
   Stereo evaluation - disabling median scaling, scaling by 5.4

   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.099  &   0.775  &   4.570  &   0.186  &   0.893  &   0.961  &   0.981  \\
